import type { ProductConfig } from './types';

/**
 * 监控产品池 v0.6 — Doubao 扩展批次（2026-04-30）
 *
 * 演进：
 *   v0.4 (Sonnet × 8): 8 标的 ABC 分级
 *   v0.5 (Sonnet × 12): 补 4 只 → core 3 / supporting 3 / watch 6
 *   v0.6 (Doubao × 11): 加 11 只新 watch（新 stage 3 通过的，未经 Sonnet WebSearch 兜底）
 *
 * 当前总数：12 (Sonnet 评估) + 11 (Doubao 评估) = 23 标的
 *   - core 3 (Sonnet)
 *   - supporting 3 (Sonnet)
 *   - watch 17 (6 Sonnet + 11 Doubao)
 *
 * 流水线：
 *   Stage 1 (universe seed) → Stage 2 (history + manual TTM) →
 *   Stage 3 (量化筛选) → Stage 4 (Sonnet/Doubao 6 维度评估) →
 *   Stage 5 (Opus 把关 + 风险显化)
 *
 * v0.4 → v0.5 调整（基于 Sonnet 补跑 4 只评估）：
 *   - 561580 央企红利：watch → CORE（Sonnet 25 分，政策最强支持，规模 1.5 年涨 2.4 倍）
 *   - 508058 厦门安居：watch → SUPPORTING（覆盖率 102% 健康，岛内扩募已受理）
 *   - 508028 国电投新能源：core → SUPPORTING（Sonnet 23 分，可分配 -14%，依赖保理）
 *   - 180602 印力消费：watch（保持，万科系流动性危机风险传导）
 *
 * Tier 含义：
 *   - core (3 只)：A 24-25 分，政策强支持 + 扩募预期，可优先建仓
 *   - supporting (3 只)：A 22-24 分，合格但有特殊处理 / 等条件
 *   - watch (6 只)：A 22 / B+ 18-20 分，留池但暂不建仓
 *
 * ttmDividend 仍手动维护（dividend API 当前不可用）。
 * 每次新分红公告 → 回到 manual_dividend_overrides.json 更新。
 */
export const PRODUCTS: ProductConfig[] = [
  // ════════════════════════════════════════════════════════
  // 🥇 CORE — 3 只，可优先建仓的核心持仓
  // ════════════════════════════════════════════════════════
  {
    code: '180601',
    name: '华夏华润商业 REIT',
    shortName: '华润商业 REIT',
    market: 'sz',
    category: 'reit',
    tier: 'core',
    grade: 'A',
    qualityScore: 24,
    redFlags: [
      'WALE 仅 1.99 年（短租约结构）',
      '底层资产单一（青岛万象城），扩募完成前集中度高',
      '当前价格使分派率仅 3.64%，溢价偏高',
    ],
    tierReason: '扩募已实质推进（昆山 + 萧山/沈阳/淄博四项目受理），等价格回调到 8.5 元',
    ttmDividend: 0.3651,
    ttmDividendAsOf: '2026-02-28',
    navRefPrice: 6.53,
    navAsOf: '2025-12-31',
    watchYield: 4.3,
    buyYield: 4.8,
    watchPrice: 8.5,
    buyPrice: 8.0,
    notes: '青岛万象城。出租率 99%+ 客流 +10.9%。华润 92 个万象城在营 / 规划 127 个，扩募节奏全市场最快',
  },
  {
    code: '512890',
    name: '红利低波 ETF（华泰柏瑞）',
    shortName: '红利低波 50',
    market: 'sh',
    category: 'dividend_etf_a',
    tier: 'core',
    grade: 'A',
    qualityScore: 25,
    redFlags: [
      '行业高度集中：银行 37.5% + 煤炭 15.3%（前两合计 52%）',
      'ETF 分红需累计报酬超指数 1%，分红确定性低于 REIT',
      '同赛道 16 只 ETF 竞争',
    ],
    tierReason: 'A 股红利 ETF 最优（Sonnet 25 分），跟踪 H30269 含分红正增长筛选，规模 307 亿',
    ttmDividend: 0.060,
    ttmDividendAsOf: '2025-10-31',
    watchYield: 4.8,
    buyYield: 5.2,
    notes: '中证红利低波 H30269（50 只样本，前 10 集中 27%）。柳军 2018-12 起任职，6 年全部正收益。新国九条 + 险资入市政策强利好',
  },
  {
    code: '561580',
    name: '央企红利 ETF（华泰柏瑞）',
    shortName: '央企红利',
    market: 'sh',
    category: 'dividend_etf_a',
    tier: 'core',
    grade: 'A',
    qualityScore: 25,
    redFlags: [
      '金融（银行）板块 33.5% + 前 10 集中 60%+',
      '费率 0.60% 高于同类红利低波 100（0.15%）',
      '运营仅 3 年（2023-05 上市），未经历完整周期',
      '富国 159332 同跟踪 000825 形成竞争',
    ],
    tierReason: '政策最强支持赛道（国资委市值管理 + 央企分红考核 + 新国九条三重利好），规模 1.5 年涨 2.4 倍',
    ttmDividend: 0.05,
    ttmDividendAsOf: '2026-04-28',
    watchYield: 4.5,
    buyYield: 5.0,
    notes: '中证央企红利指数 000825（50 只央企含中国神华/中国移动/建行）。规模 6.4 亿（2024 末）→ 15.35 亿（2026-03）',
  },

  // ════════════════════════════════════════════════════════
  // 🥈 SUPPORTING — 3 只，合格但需 caveat
  // ════════════════════════════════════════════════════════
  {
    code: '508077',
    name: '华夏基金华润有巢 REIT',
    shortName: '有巢保租房 REIT',
    market: 'sh',
    category: 'reit',
    tier: 'supporting',
    grade: 'A',
    qualityScore: 22,
    redFlags: [
      '⚠️ 2024 实际分配 6541 万 > 可分配 4904 万（超额 33%），消耗净资产',
      '基金份额净值自成立累计 -7.4%（2.4310 → 2.2508）',
      '公寓 WALE 仅 0.52 年',
      '商业部分出租率仅 63%（同比 -8.55pct）',
      '扩募后预测分派率仅 3.3%（低于当前 4.75%），存在摊薄压力',
    ],
    tierReason: '保租房政策 5 分但超额分配是隐藏问题，等可分配覆盖率回到 100%+ 再加仓',
    ttmDividend: 0.13,
    ttmDividendAsOf: '2025-12-31',
    navRefPrice: 2.34,
    navAsOf: '2025-12-31',
    watchYield: 4.5,
    buyYield: 4.8,
    watchPrice: 2.7,
    buyPrice: 2.45,
    notes: '上海松江有巢泗泾 + 东部经开区保租房。央企华润背景。马桥项目扩募 2024-11 受理',
  },
  {
    code: '508058',
    name: '中金厦门安居 REIT',
    shortName: '厦门安居',
    market: 'sh',
    category: 'reit',
    tier: 'supporting',
    grade: 'A',
    qualityScore: 24,
    redFlags: [
      '集美区岛外，租金单价（约 34 元/sqm/月）和增速低于厦门岛内',
      '扩募拟引入公租房（仁和公寓），政策管控更严，可能拉低组合租金',
      '基金净资产 2024 年 -2.52%（折旧摊销，REITs 通性）',
    ],
    tierReason: '✅ 关键：覆盖率 102% 健康（不像 508077 超额分配）。岛内扩募已 2025-04 受理，地段升级',
    ttmDividend: 0.12,
    ttmDividendAsOf: '2026-04-28',
    navRefPrice: null as unknown as undefined,
    watchYield: 4.5,
    buyYield: 5.0,
    notes: '厦门集美区园博/珩琦公寓（4665 套）。出租率 99.7%+ 个人租户 93.86%。拟扩募林边（思明）+ 仁和（湖里）→ 岛内核心',
  },
  {
    code: '510880',
    name: '上证红利 ETF（华泰柏瑞）',
    shortName: '上证红利',
    market: 'sh',
    category: 'dividend_etf_a',
    tier: 'supporting',
    grade: 'A',
    qualityScore: 23,
    redFlags: [
      '⚠️ 费率 0.60% 偏高（行业头部已降至 0.20%），长期持有成本劣势',
      '选股仅限上交所（不含深市/北交所）',
      '单因子（仅股息率），周期股分红可持续性存疑',
    ],
    tierReason: '老牌但费率高，等降费后再加；当前 19 年记录是真的护城河',
    ttmDividend: 0.142,
    ttmDividendAsOf: '2026-01-21',
    watchYield: 4.5,
    buyYield: 5.0,
    notes: 'A 股最老牌红利 ETF（2006 成立）。上证红利指数 000015，规模 192 亿。连续 15 年分红，6 年正收益累计利润 76 亿',
  },

  // ════════════════════════════════════════════════════════
  // 🥉 WATCH — 6 只，留池但暂不建仓
  // ════════════════════════════════════════════════════════
  {
    code: '508028',
    name: '中信建投国家电投新能源 REIT',
    shortName: '国电投新能源',
    market: 'sh',
    category: 'reit',
    tier: 'watch',
    grade: 'A',
    qualityScore: 23,
    redFlags: [
      '⚠️ 2025 可分配 -14.13%（66907 vs 上年 77917 万）',
      '⚠️ Q3 单季可分配 -979 万（电网停电 14 天 + 风速偏低）',
      '⚠️ 国补保理融资 38.18 亿，依赖保理融资完成分配',
      '⚠️ 2026-03-30 战略配售解禁 24.7%（已发生），流通盘扩大',
      '电力市场化交易敞口扩大（已 8.02%）',
      '送出线路单一，电网停电直接影响发电量',
    ],
    tierReason: 'Sonnet 23 分，从 core 降级。等可分配恢复 + 滨海~鹤栖 500kV 投运',
    ttmDividend: 0.30,
    ttmDividendAsOf: '2026-01-05',
    watchYield: 5.0,
    buyYield: 5.5,
    notes: '江苏盐城滨海北 H1/H2 海上风电（500MW）。央企国家电投。海风 50% 增值税即征即退延续到 2027-12',
  },
  {
    code: '180602',
    name: '中金印力消费 REIT',
    shortName: '印力消费 REIT',
    market: 'sz',
    category: 'reit',
    tier: 'watch',
    grade: 'A',
    qualityScore: 22,
    redFlags: [
      '⚠️ 万科系流动性危机：万科 2025Q3 现金短债比 0.43，运营资源 + 品牌稳定性受联动',
      '底层单一资产（西溪印象城），高度依赖杭州城西',
      'WALE 仅 2.53 年（短租）',
      '管理费 4052 万 > 净利润 1929 万，费用结构偏高',
      '2025-11 万科展期后 REIT 单日跌 2.7%',
    ],
    tierReason: '资产本身健康（覆盖率 102-104%），但万科系风险传导是结构性问题',
    ttmDividend: 0.0856,
    ttmDividendAsOf: '2025-12-31',
    navRefPrice: 3.26,
    navAsOf: '2025-08-14',
    watchYield: 3.5,
    buyYield: 4.2,
    watchPrice: 3.8,
    buyPrice: 3.4,
    notes: '杭州西溪印象城（印力/万科）。出租率 99%+ 客流 +10.72%。等万科流动性危机化解',
  },
  {
    code: '513530',
    name: '港股通红利 ETF（华泰柏瑞）',
    shortName: '港股通红利',
    market: 'sh',
    category: 'dividend_etf_hk',
    tier: 'watch',
    grade: 'B+',
    qualityScore: 20,
    redFlags: [
      '⚠️ QDII 额度紧张：21.63% 资产已转港股通渠道，红利税升至 20%',
      '30 只样本前 4 行业集中 68%（银行+交运+煤炭+石油）',
      '最大回撤 18.4% + 汇率波动',
      '2026-04 份额从 22.52 亿降至 19.60 亿（-13%）',
    ],
    tierReason: 'QDII 税收优势已部分稀释；等额度恢复或港股估值修复',
    ttmDividend: 0.10,
    ttmDividendAsOf: '2026-03-17',
    watchYield: 5.2,
    buyYield: 5.8,
    notes: '中证港股通高股息（930915）QDII 模式。理论税收优势 vs 港股通 20%，但额度紧张已实质打折',
  },
  {
    code: '180202',
    name: '华夏越秀高速 REIT',
    shortName: '越秀高速 REIT',
    market: 'sz',
    category: 'reit',
    tier: 'watch',
    grade: 'B+',
    qualityScore: 18,
    redFlags: [
      '⚠️ 2024 可分配金额同比 -22%，2025Q2 通行费同比 -6.86%',
      '⚠️ 折旧摊销 2025Q2 同比 +23.26%（成本结构性上升）',
      '⚠️ 合并资产负债率 86.6%（含 ABS 内部债）',
      '⚠️ 特许经营权剩余约 10 年（2036-12 到期），净值趋零',
      '京港澳改扩建持续分流，竞争路网趋于成熟',
      '无任何扩募进展，单一资产 + 资产老化',
    ],
    tierReason: '7% 分派率是衰退预期 price-in 的结果。当 11 年期到期归零债看，单只 ≤ 10w',
    ttmDividend: 0.38175,
    ttmDividendAsOf: '2026-01-31',
    navRefPrice: 6.08,
    navAsOf: '2025-06-30',
    watchYield: 4.8,
    buyYield: 5.5,
    notes: '湖北汉孝高速（武汉-孝感 33km）。"越秀"是原始权益人非地名。Sonnet 18 分严格降级',
  },
  {
    code: '508098',
    name: '嘉实京东仓储基础设施 REIT',
    shortName: '京东物流',
    market: 'sh',
    category: 'reit',
    tier: 'watch',
    grade: 'B+',
    qualityScore: 18,
    redFlags: [
      '⚠️ 100% 京东系关联方租户，单一企业生态圈风险',
      '⚠️ 廊坊 2026-05 起续租降租 30%（39.39 → 27.68 元/sqm/月）',
      '⚠️ 重庆 2025 年起降租，武汉 2024 年起降租 13%',
      '⚠️ NOI 连续下行：2025 收入 -1.77% / 现金流 -10.05% / Q1 可分配 -14.44%',
      '廊坊周边市场租金已较 2020 年腰斩',
      '关联交易定价独立性存疑',
    ],
    tierReason: '所有 3 处资产都在降租；等续租企稳或资产分散后再考虑',
    ttmDividend: 0.18,
    ttmDividendAsOf: '2026-01-22',
    navRefPrice: 3.47,
    navAsOf: '2025-12-31',
    watchYield: 5.0,
    buyYield: 5.5,
    notes: '京东重庆/武汉/廊坊 3 处仓库（35.1 万 sqm）。出租率 100% 但租金连续下调',
  },
  {
    code: '515100',
    name: '红利低波 100 ETF（景顺长城）',
    shortName: '红利低波 100',
    market: 'sh',
    category: 'dividend_etf_a',
    tier: 'watch',
    grade: 'B+',
    qualityScore: 20,
    redFlags: [
      '⚠️ 2025 年分红 0.1053 元 vs 2023 年 0.4370 元，下降 76%',
      '指数不含 ROE 筛选（vs 512890 H30269 含分红正增长筛选）',
      '钢铁（9%）+ 化工（8%）周期股占比高',
      '现任经理 2023-11 才接管，记录仅 2.5 年',
    ],
    tierReason: '同 A 股红利低波，512890 已升 core；这只让位',
    ttmDividend: 0.064,
    ttmDividendAsOf: '2026-04-16',
    watchYield: 4.8,
    buyYield: 5.2,
    notes: '中证红利低波 100（930955）。景顺长城管理。规模 62 亿同类第一但 Sonnet 评分降到 B+',
  },

  // ════════════════════════════════════════════════════════
  // 🆕 Doubao 新评估批次（2026-04-30，全部 watch tier 待人工复核）
  // 来自 Stage 4 (LLM_PROVIDER=doubao)，无 WebSearch 兜底
  // 数据：data/quality_scores_doubao.json
  // ════════════════════════════════════════════════════════
  {
    code: '508056',
    name: '中金普洛斯 REIT',
    shortName: '普洛斯物流',
    market: 'sh',
    category: 'reit',
    tier: 'watch',
    grade: 'A+',
    qualityScore: 27,
    redFlags: [
      '历史最大回撤 56%，市场波动风险',
      '2023 年分派率从上市初期已显著下降',
    ],
    tierReason: 'Doubao A+ 27 — 物流 REIT 旗舰（普洛斯 7 处物流园），但需 Sonnet 验证 / 人工复核扩募节奏',
    ttmDividend: 0.1825,
    ttmDividendAsOf: '2026-04-01',
    watchYield: 5.0,
    buyYield: 5.5,
    notes: '北京空港 / 上海青浦 / 广州保税 / 佛山 / 苏州 / 武汉 / 成都 7 处物流园。中金 + 普洛斯中国（首批 REIT）',
  },
  {
    code: '508033',
    name: '易方达深高速 REIT',
    shortName: '深高速',
    market: 'sh',
    category: 'reit',
    tier: 'watch',
    grade: 'A+',
    qualityScore: 26,
    redFlags: [
      '高速 REIT 通病：特许经营权到期归零（参考 180202）',
      '收费标准受政府定价限制',
      '宏观经济波动影响通行量',
    ],
    tierReason: 'Doubao A+ 26 — 但高速 REIT 必须当"X 年期高息债"看，建仓前必须确认特许期剩余',
    ttmDividend: 0.705,
    ttmDividendAsOf: '2026-04-30',
    watchYield: 5.5,
    buyYield: 6.0,
    notes: '机荷高速西段 + 盐排高速 + 南光高速。易方达 + 深圳高速。当前分派率 10.88% 极高（部分反映到期归零折现）',
  },
  {
    code: '180401',
    name: '鹏华深圳能源 REIT',
    shortName: '深圳能源',
    market: 'sz',
    category: 'reit',
    tier: 'watch',
    grade: 'A',
    qualityScore: 24,
    redFlags: [
      '客户集中度极高（单一电网）',
      '电价政策变动风险',
      '光伏依赖光照条件',
    ],
    tierReason: 'Doubao A 24 — 与 508028 国电投新能源同类（能源），但底层是光伏（红泥湾/惠州/梅州）',
    ttmDividend: 0.5559,
    ttmDividendAsOf: '2026-04-30',
    watchYield: 5.0,
    buyYield: 5.5,
    notes: '深圳能源红泥湾 + 惠州稔山 + 梅州梅县光伏电站。鹏华 + 深能集团（深圳国资）',
  },
  {
    code: '508006',
    name: '富国首创水务 REIT',
    shortName: '首创水务',
    market: 'sh',
    category: 'reit',
    tier: 'watch',
    grade: 'A',
    qualityScore: 23,
    redFlags: [
      '历史最大回撤 69%（极高）',
      '3 年股息率均值 0%（数据不全）',
    ],
    tierReason: 'Doubao A 23 — 市政水务，特许经营 + 政府付费稳定，但回撤大需观察',
    ttmDividend: 0.4445,
    ttmDividendAsOf: '2026-04-03',
    watchYield: 5.5,
    buyYield: 6.0,
    notes: '北京小红门 + 深圳福永 + 合肥十五里河污水处理厂。富国 + 首创集团（北京国资）。市政 REIT 首批',
  },
  {
    code: '180801',
    name: '中航首钢绿能 REIT',
    shortName: '首钢绿能',
    market: 'sz',
    category: 'reit',
    tier: 'watch',
    grade: 'A',
    qualityScore: 24,
    redFlags: [
      '租户 100% 政府单一客户（垃圾处理费）',
      '政策补贴变动风险',
      '2023 年垃圾处理单价 -2.1%',
    ],
    tierReason: 'Doubao A 24 — 北京门头沟首钢生物质能源（垃圾焚烧发电）',
    ttmDividend: 1.0710,
    ttmDividendAsOf: '2026-04-23',
    watchYield: 5.0,
    buyYield: 5.5,
    notes: '北京门头沟生活垃圾焚烧发电（鲁家山）。首钢集团 + 中航基金。当前分派率 9.05% 高',
  },
  {
    code: '180302',
    name: '华夏深国际 REIT',
    shortName: '深国际物流',
    market: 'sz',
    category: 'reit',
    tier: 'watch',
    grade: 'A',
    qualityScore: 24,
    redFlags: [
      '前 5 大租户集中度 42%（略高）',
      '资产负债率近 50% 预警线',
    ],
    tierReason: 'Doubao A 24 — 与 508056 普洛斯同类物流，但深国际单一项目',
    ttmDividend: 0.1879,
    ttmDividendAsOf: '2026-04-15',
    watchYield: 5.5,
    buyYield: 6.0,
    notes: '深圳综合物流港。华夏 + 深国际控股集团（深圳国资）',
  },
  {
    code: '180501',
    name: '红土创新深圳安居 REIT',
    shortName: '深圳安居',
    market: 'sz',
    category: 'reit',
    tier: 'watch',
    grade: 'A',
    qualityScore: 23,
    redFlags: [],
    tierReason: 'Doubao A 23 — 与 508077/508058 同保租房类。深圳人才安居',
    ttmDividend: 0.1195,
    ttmDividendAsOf: '2026-04-10',
    watchYield: 4.5,
    buyYield: 5.0,
    notes: '凤凰公馆 / 龙悦居四期 / 坪河雅苑（深圳保租房）。红土创新（深创投）+ 深圳安居',
  },
  {
    code: '508088',
    name: '国泰海通东久新经济 REIT',
    shortName: '东久新经济',
    market: 'sh',
    category: 'reit',
    tier: 'watch',
    grade: 'B+',
    qualityScore: 21,
    redFlags: [
      '2023 年出租率较上年 -2pct 至 92%',
      '前三大租户集中科技制造业',
    ],
    tierReason: 'Doubao B+ 21 — 与 508027/508003 等产业园 REIT 同类',
    ttmDividend: 0.2772,
    ttmDividendAsOf: '2026-04-28',
    watchYield: 5.5,
    buyYield: 6.0,
    notes: '上海临港奉贤 + 苏州工业园 + 南京江宁产业园。国泰海通（合并后）+ 东久',
  },
  {
    code: '508009',
    name: '中金安徽交控 REIT',
    shortName: '安徽交控',
    market: 'sh',
    category: 'reit',
    tier: 'watch',
    grade: 'B+',
    qualityScore: 19,
    redFlags: [
      '可分配金额覆盖率不足 100%',
      '2023H1 NOI 同比下降',
      '高速 REIT 到期归零特性',
    ],
    tierReason: 'Doubao B+ 19 — 合安高速（合肥-安庆）。NOI 下行趋势注意',
    ttmDividend: 0.685,
    ttmDividendAsOf: '2026-04-01',
    watchYield: 5.5,
    buyYield: 6.0,
    notes: '合安高速公路（合肥至安庆段）。中金 + 安徽交控集团',
  },
  {
    code: '508005',
    name: '华夏首创奥莱 REIT',
    shortName: '首创奥莱',
    market: 'sh',
    category: 'reit',
    tier: 'watch',
    grade: 'B+',
    qualityScore: 19,
    redFlags: [
      '2023Q2 杭州项目出租率环比 -2.1pct',
      '消费复苏不及预期影响客流',
    ],
    tierReason: 'Doubao B+ 19 — 奥莱业态周期下行风险高于一线核心商业（如 180601 万象城）',
    ttmDividend: 0.1978,
    ttmDividendAsOf: '2026-03-06',
    watchYield: 4.8,
    buyYield: 5.5,
    notes: '北京房山 + 杭州富阳奥特莱斯。华夏 + 首创集团',
  },
  {
    code: '508027',
    name: '东吴苏园产业 REIT',
    shortName: '苏园产业',
    market: 'sh',
    category: 'reit',
    tier: 'watch',
    grade: 'B+',
    qualityScore: 17,
    redFlags: [
      '最大回撤 52%（高）',
      '资产负债率 55%（高杠杆）',
      '3 年股息率均值 0%（不稳定）',
    ],
    tierReason: 'Doubao B+ 17 — 苏州工业园 BioBAY 生物医药园。回撤 + 杠杆都偏高',
    ttmDividend: 0.3124,
    ttmDividendAsOf: '2026-04-23',
    watchYield: 5.5,
    buyYield: 6.0,
    notes: '苏州生物医药产业园（BioBAY）一期、二期。东吴 + 苏州工业园区运营',
  },
];

export function findProduct(code: string): ProductConfig | undefined {
  return PRODUCTS.find((p) => p.code === code);
}

/** Tier 排序权重，用于 dashboard 排序 */
export const TIER_ORDER: Record<string, number> = {
  core: 0,
  supporting: 1,
  watch: 2,
};
